---
title: "Posts"
site: distill::distill_website
listing: posts
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<br> </br>

```{r}
library(XML)
library(leaflet)
myfunction <- function(myfile){
  pfile <- htmlTreeParse(file = myfile, 
                         error = function(...) {}, useInternalNodes = T)
  coords <- xpathSApply(pfile, path = "//trkpt", xmlAttrs)
  gps <- data.frame(t(coords))
  gps$lat <- as.numeric(gps$lat)
  gps$lon <- as.numeric(gps$lon)
  return(gps)
}
fls <- list.files("docs/", recursive = TRUE, full.names = TRUE)
fls <- fls[grep(".gpx", fls)]
markers <- read.csv("markers.csv")
colnames(markers)[1] <- "lat"

m <- leaflet(width = "100%") %>% 
  addTiles() %>%
    addMarkers(lat = markers$lat, lng = markers$lon, 
               popup = paste0('<a href="', markers$link, '">', markers$title, '</a>'),
               options = popupOptions(closeButton = FALSE)) %>%
  
  # Add tiles
  addProviderTiles("OpenStreetMap.Mapnik", group = "OpenStreetMap") %>%
  addProviderTiles("OpenTopoMap", group = "OpenTopoMap") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
  
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("OpenStreetMap", "OpenTopoMap", "Satellite"),
                   options = layersControlOptions(collapsed = FALSE)) 

for(i in seq(length(fls))){
  gps1 <- myfunction(fls[i])
  m <- m %>% 
    addPolylines(data = gps1, 
                 lng = ~lon, 
                 lat = ~lat,
                 color = "#DF536B", opacity = 0.7)
}

m
```
