---
title: "Cinque Terre"
description: |
  A short description of the post.
categories:
  - Liguria
  - trekking
author:
  - name: Mar
date: 2022-02-28
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(XML)
library(leaflet)
myfunction <- function(myfile){
  pfile <- htmlTreeParse(file = myfile, 
                         error = function(...) {}, useInternalNodes = T)
  coords <- xpathSApply(pfile, path = "//trkpt", xmlAttrs)
  gps <- data.frame(t(coords))
  gps$lat <- as.numeric(gps$lat)
  gps$lon <- as.numeric(gps$lon)
  return(gps)
}
gps1 <- myfunction("alta-via-delle-5-terre.gpx")
gps2 <- myfunction("alta-via-de-golfo.gpx")

fls <- list.files(full.names = TRUE)
fls <- fls[grep(".gpx", fls)]
fls <- fls[grep("verde", fls)]
i <- 1
gps3 <- myfunction(fls[i])
for(i in 2:length(fls)){
  gps3 <- rbind(gps3, myfunction(fls[i]))
}


leaflet(gps1, width = "100%") %>% 
  addTiles() %>% 
  addPolylines(data = gps1, 
               lng = ~lon, 
               lat = ~lat,
               color = "#DF536B", opacity = 0.7)  %>% 
  addPolylines(data = gps2, 
               lng = ~lon, 
               lat = ~lat,
               color = "#377EB8", opacity = 0.7)  %>% 
  addPolylines(data = gps3, 
               lng = ~lon, 
               lat = ~lat,
               color = "#984EA3", opacity = 0.7) %>%
  
  # Add tiles
  addProviderTiles("OpenStreetMap.Mapnik", group = "OpenStreetMap") %>%
  addProviderTiles("OpenTopoMap", group = "OpenTopoMap") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
  
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("OpenStreetMap", "OpenTopoMap", "Satellite"),
                   options = layersControlOptions(collapsed = FALSE)) 
```

Source:  
  
- Alta Via delle 5 Terre: https://hiking.waymarkedtrails.org/#route?id=1652359&type=relation&map=12.0/44.1887/9.9018   
- Alta Via de Golfo: https://hiking.waymarkedtrails.org/#route?id=3980609&type=relation  
- Sentiero Verdeazzurro:  
  * https://hiking.waymarkedtrails.org/#route?id=3984226&type=relation&map=10.0/44.2213/9.6291  
  * https://hiking.waymarkedtrails.org/#route?id=7798215&type=relation  
  * https://hiking.waymarkedtrails.org/#route?id=7798145  
  * https://hiking.waymarkedtrails.org/#route?id=7797964  
  * https://hiking.waymarkedtrails.org/#route?id=7797939  
- https://maremonte.github.io/planning/posts/2022-02-28-cinque-terre/map.html